<?php

use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('skills')->insert([
            [
                'industry_id' => 1,
                'skill_name' => 'Singing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Dancing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Emceeing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rapping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Acting',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Photography/Videography',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Animation',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Catering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Animation',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Production(Poducer)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Choreography',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Audio Enginering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Content writing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rapping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Make up artistry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Voice over artistry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Comedy',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Football',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Basketball',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Volleyball',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Martial arts',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Software & Development(Computer)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Software Design work',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Networking/Network management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Computer Repair and Maintenance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Phone repair & maintenance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Plumbing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wiring',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Interior design/decoration',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Architecture',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Volunteering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Masonry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Sales & marketing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Human Resourse management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Livestock farming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bee keeping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fish farming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Poultry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => -1,
                'skill_name' => 'Research specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Driving',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Counselling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Teaching',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auditing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Accounting',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Health care & nursing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Clearing & forwarding',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Food/Nutrition',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Catering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cyber security',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Banking',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Training',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Instrument playing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Manual labour',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Gym instruction',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Foreign language',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forex trade',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'House keeping/management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Kabadii',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Boxing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bike Racing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fencing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Tennis',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Badminton',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wrestling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cricket',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Golf',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Javelin',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rugby',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Table tennis',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Aerobics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Gymnastics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Running',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Skating',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Long Jump/High Jump',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Pole Vault',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Badminton',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bowling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Poultry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Hydroponics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Swimming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Mechanic',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Insurance specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Beautician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Saloonist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Hairdressing & beauty',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cosmetology',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Pedicure & manicure',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Massage therapy',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Journalism',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Radio presenter',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'TV presenter',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'News broadcasting',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Advertising, Prmotions and Marketing specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Technical writers',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Graphic design',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Writers & authors',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Editors',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Film & Video editors',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Camera specialist/operators',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Interpretors & Translators',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Reporters, Correspondents & Boadcats news analysts',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Sound engineering technician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Commentry & announcing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'zoologist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'wildlife specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Food scientist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Agricultural engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Water/waste water engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Environmental engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Water resource specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Animal husbandry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fish monger',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forest and conservation  worker',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forester',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Conservation scientist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forest and conservation technician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Ecologist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Firefighter',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Conservation officer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forestry consultant',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'GIS Specialist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Land manager',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Outdoor adventure guide',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Park warden/planner',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Naturalist',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => '',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Quality testing engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Tyre technician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Vehicle inspector',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auto instructor',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auto body repair technician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auto electrician',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auto engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Process engineer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Audo designer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auto paint',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => -1,
                'skill_name' => 'Quality Assuarance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => '',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Corporate & Institutional banker',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Investment banker(capital markets)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Markets(Sales & Trading)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Business banking',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Ratail/Consumer banking',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Private equity',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Hedge funds',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Trading',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Portfolio/Asset management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wealth management/private banking',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Personal finance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Financial consultant',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Compliance officer',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Risk management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Government & Financial regulators',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Corporate financing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Tax advisory',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fintech and start-ups',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Laravel',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wordpress',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'CodeIgniter',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Joomla',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Drupal',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'CMS',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'PHP',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'C#',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'C++',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'C',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Java',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Python',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Ruby',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Ruby & Rails',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Flutter',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Javascript',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Dart',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Go',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Swift',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Kotlin',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Pearl',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Scala',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rust',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Mobile Development',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Web development',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Desktop application dvelopment',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Vue JS',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Angular',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Node JS',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'React',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'React Native',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'MySQL',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'POSTGRE SQL',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Oracle',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'jQuery',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cloudera',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'MongoDB',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Microsoft SQL server',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'IBM DB2',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Redis',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'MariaDB',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ]);
    }
}
