<?php

use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('account_types')->insert([
            [
                'industry_id' => 1,
                'skill_name' => 'Singing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Dancing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Emceeing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rapping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Acting',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Photography/Videography',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Animation',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Catering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Animation',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Production(Poducer)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Choreography',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Audio Enginering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Content writing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rapping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Make up artistry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Voice over artistry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Comedy',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Football',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Basketball',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Volleyball',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Martial arts',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Software & Development(Computer)',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Software Design work',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Networking/Network management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Computer Repair and Maintenance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Phone repair & maintenance',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Plumbing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wiring',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Interior design/decoration',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Architecture',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Volunteering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Masonry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Sales & marketing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Human Resourse management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Livestock farming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bee keeping',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fish farming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Poultry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Research',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Driving',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Counselling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Teaching',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Auditing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Accounting',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Health care & nursing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Clearing & forwarding',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Food/Nutrition',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Catering',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cyber security',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Banking',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Training',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Instrument playing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Manual labour',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Gym instruction',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Foreign language',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Forex trade',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'House keeping/management',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Kabadii',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Boxing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bike Racing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Fencing',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Tennis',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Badminton',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Wrestling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Cricket',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Golf',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Javelin',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Rugby',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Table tennis',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Aerobics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Gymnastics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Running',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Skating',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Long Jump/High Jump',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Pole Vault',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Badminton',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Bowling',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Poultry',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Hydroponics',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'industry_id' => 1,
                'skill_name' => 'Swimming',
                'order' => 1,
                'active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ]);
    }
}
