<?php

use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('towns')->insert([
            [
                'county_id' => 1,
                'town_name' => 'Nairobi town',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Buruburu,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Umoja 1,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Donholm,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruaka,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruaraka,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Dandora,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kayole,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Utawala,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Embakasi,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kariobangi,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Makadara,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'CBD',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Runda,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Muthaiga,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kilimani,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Westlands,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruiru,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kasarani,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Pipeline,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Tassia,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kileleshwa,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Gigiri,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kitisuru,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Rosslyn,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Hurlingham,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Upper Hill,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ridgeways,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Riverside,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Spring Valley,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Nyari,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Whispers,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kyuna,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Lavington,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Karen,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Lower Kabete,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Loresho,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Fedha Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Garden Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mirema Drive,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Thindigua Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Thome Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Membly Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Greenspan,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Komarock,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Chokaa,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruai,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Njiru,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Tel Aviv Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Umoja 2,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Umoja 3,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Nasra Gardens,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kawangware,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Langata,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Two Rivers,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mihango,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Industrial Area,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Eagle Plains Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kibera,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mukuru kwa Ruben,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mukuru kwa Njenga,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'ABC Place,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ziwani Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Imara Gardens Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Imara Daima,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kamulu,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Marurui,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Garden City,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Githurai,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'TRM/Thika Road Mall,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Burhan Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Sossiani Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Zimmerman,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Old Posta Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kahawa North,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kahawa Sukari,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mwiki,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Riverside,Kamulu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'JKIA,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Syokimau,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Multimedia University,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Dagoreti,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kangemi,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kagondo,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Muthangari,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kibagare,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Parklands,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'City Park Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Balozi Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Clay Works,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kamiti,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kahawa West,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Gathecha Village,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Messo Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mowlem,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Harambee Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Survey,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mathare,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Huruma,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Eistleigh North,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Pangani,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Pumwani,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Eistleigh,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ngara West,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ngara,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Shauri Moyo,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kimathi,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Bahati,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Jericho,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ofafa,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Makongeni Maisha,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Hamza,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Tena,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Lumumba,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Baraka,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Viwandani,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mukuru Kayaba,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Akiba Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kenyatta Hospital,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'South B,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'South C,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Nairobi West,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ayany Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kibera,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Jamhuri,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Woodley,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Thompson Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Riruta,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kuwinda,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Gwengwa Gardens,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Barton Estate,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Saika,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Nairobi South,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mbotela,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Jericho,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Drive Inn,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Fanusi,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Innercore,Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Mombasa town',
                'created_by' => 1,
                'updated_by' => 1,
            ],
                        [
                'county_id' => 2,
                'town_name' => 'Nyali Estate,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Kizingo Estate,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Bamburi,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Kibokoni,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Ganjoni,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Tudor,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Likoni,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Magongo,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Mikindani,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Changamwe,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Port Reitz,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Shanzu,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Kisauni,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Majengo,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Mshoromoni,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Barsheba,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Mtongwe,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Kongowea,Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Kisumu town,',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Kondele,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Manyatta,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Tom Mboya,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Polyview,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Nyalenda,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Migosi,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Nyamasaria,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Riat,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Milimani,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Okore,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Mamboleo,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Kenya RE,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Lolwe Estate,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Obunga,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Bandani,Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Nakuru town',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Racecourse,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Milimani,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Section 58,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Whitehouse Estate,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Langa Langa,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'London,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Satelite Estate,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Naka Estate,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Bahati Estate,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Lanet,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Freehold,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Kiamunyi,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Mawanga,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Mwariki,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Pipeline,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Pangani,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Ngata,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Bondeni,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Bangladesh,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Shabab,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Kaptembwa,Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 5,
                'town_name' => 'Narok',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 6,
                'town_name' => 'Kisii',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 7,
                'town_name' => 'Nyamira',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 8,
                'town_name' => 'Kwale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 9,
                'town_name' => 'Kilifi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 10,
                'town_name' => 'Hola',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 11,
                'town_name' => 'Lamu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 12,
                'town_name' => 'Mwatate',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 13,
                'town_name' => 'Garissa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 14,
                'town_name' => 'Wajir',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 15,
                'town_name' => 'Mandera',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 16,
                'town_name' => 'Marsabit',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 17,
                'town_name' => 'Isiolo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 18,
                'town_name' => 'Meru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 19,
                'town_name' => 'Kathwana',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 20,
                'town_name' => 'Embu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 21,
                'town_name' => 'Kitui',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 22,
                'town_name' => 'Machakos',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Wote',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 24,
                'town_name' => 'Ol Kalou',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Nyeri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 26,
                'town_name' => 'Kerugoya',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 27,
                'town_name' => 'Muranga',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Kiambu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Lodwar',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 30,
                'town_name' => 'Kapenguria',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 31,
                'town_name' => 'Maralal',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 32,
                'town_name' => 'Kitale',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 33,
                'town_name' => 'Eldoret town',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Huruma,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Mwanzo Estate,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Elgon View,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Pioneer Estate,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Kapsoya,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'West Indies,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Langas Estate,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Action Estate,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Annex Estate,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Kimumu,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Jerusalem,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Sogomo,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 33,
            'town_name' => 'Maili Nne,Eldoret',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
                'county_id' => 34,
                'town_name' => 'Iten',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 35,
                'town_name' => 'Kapsabet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 36,
                'town_name' => 'Kabarnet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 37,
                'town_name' => 'Nanyuki',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Kajiado',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Kericho',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 40,
                'town_name' => 'Bomet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 41,
                'town_name' => 'Kakamega',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 42,
                'town_name' => 'Vihiga',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 43,
                'town_name' => 'Bungoma',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Busia',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Siaya',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Homabay',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Migori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Bondo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Kendu Bay',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Sori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Rongo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Ndhiwa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Rodi Kopany',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Mumias',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Awendo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Isbania',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Oloitoktok',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Namanga',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Isinya',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Muhoroni',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Naivasha',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Gilgil',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Magadi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 36,
                'town_name' => 'Marigat',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Ngong',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Kapedo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Kikuyu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 4,
                'town_name' => 'Njoro',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 38,
                'town_name' => 'Eldama Ravine',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Limuru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Thika',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Maguga Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Section A,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Section 2,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Ngoingwa Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Posta Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Landless Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Makongeni Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Witeithie Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Kiandutu Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Kisii Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
            'county_id' => 28,
            'town_name' => 'Kiganjo Estate,Thika',
            'created_by' => 1,
            'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Ruiru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Othaya',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Ongata Rongai',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Gatundu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Githunguri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 27,
                'town_name' => 'Kiriani',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Tetu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 12,
                'town_name' => 'Voi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 9,
                'town_name' => 'Malindi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 10,
                'town_name' => 'Bura',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 2,
                'town_name' => 'Bamburi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Gazi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Ukunda',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Athi River',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Kibwezi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Mtito Andeyi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Tala',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 19,
                'town_name' => 'Chuka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 23,
                'town_name' => 'Makindu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 21,
                'town_name' => 'Imale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Bumala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 39,
                'town_name' => 'Kericho',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 35,
                'town_name' => 'Kaimosi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Matungu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Bunyala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Nambale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Butere',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Lugulu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Shinyalu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 42,
                'town_name' => 'Lwanda',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Oyugis',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 7,
                'town_name' => 'Keroka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Koru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Maseno',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Mbita',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Migori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Ahero',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Katito',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Ugunja',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 13,
                'town_name' => 'Daadab',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Banisa',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 14,
                'town_name' => 'Bute',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Takaba',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Elwak',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 15,
                'town_name' => 'Lafey',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 44,
                'town_name' => 'Malaba',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Lunga Lunga',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Belgut',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 4,
                'town_name' => 'Mai Mahiu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 37,
                'town_name' => 'Nyahururu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 37,
                'town_name' => 'Rumuruti',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 2,
                'town_name' => 'Likoni',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 2,
                'town_name' => 'Changamwe',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 31,
                'town_name' => 'Maralal',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 2,
                'town_name' => 'Kisauni',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Lokichogio',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Kakuma',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 43,
                'town_name' => 'Webuye',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 12,
                'town_name' => 'Wundanyi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 16,
                'town_name' => 'Loiyangalani',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 21,
                'town_name' => 'Mwingi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Ngong',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Kangundo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 4,
                'town_name' => 'Molo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Londiani',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 22,
                'town_name' => 'Mlolongo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 39,
                'town_name' => 'Litein',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 32,
                'town_name' => 'Kimilili',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 9,
                'town_name' => 'Mariakani',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Awasi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 20,
                'town_name' => 'Runyenjes',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Chemelil',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Malava',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 6,
                'town_name' => 'Suneka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 6,
                'town_name' => 'Ogembo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Ukwala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 18,
                'town_name' => 'Maua',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 19,
                'town_name' => 'Chuka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 28,
                'town_name' => 'Juja',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 16,
                'town_name' => 'Moyale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 33,
                'town_name' => 'Burnt Forest',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 27,
                'town_name' => 'Maragua',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruai',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Naivasha',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Yala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 6,
                'town_name' => 'Tabaka',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 43,
                'town_name' => 'Malakisi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Kipkelion',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 7,
                'town_name' => 'Nyansiongo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Matuu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Kitengela',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 27,
                'town_name' => 'Makuyu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Karuri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 26,
                'town_name' => 'Mwea',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
               'county_id' => 17,
               'town_name' => 'Kangeta',
               'created_by' => 1,
               'updated_by' => 1,
          ],
          [    'county_id' => 17,
               'town_name' => 'Kubi Turkana',
               'created_by' => 1,
               'updated_by' => 1,
          ],
          [
               'county_id' => 17,
               'town_name' => 'Kaathene',
               'created_by' => 1,
               'updated_by' => 1,
          ],
          [
               'county_id' => 17,
               'town_name' => 'Garba',
               'created_by' => 1,
               'updated_by' => 1,
          ],
          [
               'county_id' => 17,
               'town_name' => 'Magado',
               'created_by' => 1,
               'updated_by' => 1,
          ],
          [
               'county_id' => 17,
               'town_name' => 'Kampi Ya Juu',
               'created_by' => 1,
               'updated_by' => 1,
          ]
        ]);
    }
}
