<?php

use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('towns')->insert([
            [
                'county_id' => 1,
                'town_name' => 'Nairobi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 2,
                'town_name' => 'Mombasa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Kisumu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Nakuru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 5,
                'town_name' => 'Narok',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 6,
                'town_name' => 'Kisii',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 7,
                'town_name' => 'Nyamira',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 8,
                'town_name' => 'Kwale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 9,
                'town_name' => 'Kilifi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 10,
                'town_name' => 'Hola',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 11,
                'town_name' => 'Lamu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 12,
                'town_name' => 'Mwatate',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 13,
                'town_name' => 'Garissa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 14,
                'town_name' => 'Wajir',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 15,
                'town_name' => 'Mandera',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 16,
                'town_name' => 'Marsabit',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 17,
                'town_name' => 'Isiolo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 18,
                'town_name' => 'Meru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 19,
                'town_name' => 'Kathwana',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 20,
                'town_name' => 'Embu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 21,
                'town_name' => 'Kitui',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 22,
                'town_name' => 'Machakos',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Wote',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 24,
                'town_name' => 'Ol Kalou',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Nyeri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 26,
                'town_name' => 'Kerugoya',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 27,
                'town_name' => 'Muranga',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Kiambu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Lodwar',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 30,
                'town_name' => 'Kapenguria',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 31,
                'town_name' => 'Maralal',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 32,
                'town_name' => 'Kitale',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 33,
                'town_name' => 'Eldoret',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 34,
                'town_name' => 'Iten',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 35,
                'town_name' => 'Kapsabet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 36,
                'town_name' => 'Kabarnet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 37,
                'town_name' => 'Nanyuki',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Kajiado',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Kericho',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 40,
                'town_name' => 'Bomet',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 41,
                'town_name' => 'Kakamega',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 42,
                'town_name' => 'Vihiga',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 43,
                'town_name' => 'Bungoma',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Busia',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Siaya',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Homabay',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Migori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Bondo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Kendu Bay',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Sori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Rongo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Ndhiwa',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Rodi Kopany',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Mumias',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Awendo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Isbania',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Oloitoktok',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Namanga',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Isinya',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Muhoroni',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Naivasha',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 4,
                'town_name' => 'Gilgil',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 38,
                'town_name' => 'Magadi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 36,
                'town_name' => 'Marigat',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Ngong',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 29,
                'town_name' => 'Kapedo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Kikuyu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 4,
                'town_name' => 'Njoro',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 38,
                'town_name' => 'Eldama Ravine',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Limuru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Thika',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Ruiru',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Othaya',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 38,
                'town_name' => 'Ongata Rongai',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Gatundu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 28,
                'town_name' => 'Githunguri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 27,
                'town_name' => 'Kiriani',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 25,
                'town_name' => 'Tetu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 12,
                'town_name' => 'Voi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 9,
                'town_name' => 'Malindi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 10,
                'town_name' => 'Bura',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 2,
                'town_name' => 'Bamburi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Gazi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Ukunda',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Athi River',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Kibwezi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 23,
                'town_name' => 'Mtito Andeyi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 22,
                'town_name' => 'Tala',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 19,
                'town_name' => 'Chuka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 23,
                'town_name' => 'Makindu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 21,
                'town_name' => 'Imale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Bumala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 39,
                'town_name' => 'Kericho',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 35,
                'town_name' => 'Kaimosi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Matungu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Bunyala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Nambale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Butere',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 44,
                'town_name' => 'Lugulu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 41,
                'town_name' => 'Shinyalu',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 42,
                'town_name' => 'Lwanda',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Oyugis',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 7,
                'town_name' => 'Keroka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Koru',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Maseno',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 46,
                'town_name' => 'Mbita',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 47,
                'town_name' => 'Migori',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Ahero',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 3,
                'town_name' => 'Katito',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 45,
                'town_name' => 'Ugunja',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 13,
                'town_name' => 'Daadab',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Banisa',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 14,
                'town_name' => 'Bute',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Takaba',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 15,
                'town_name' => 'Elwak',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 15,
                'town_name' => 'Lafey',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 44,
                'town_name' => 'Malaba',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 8,
                'town_name' => 'Lunga Lunga',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 39,
                'town_name' => 'Belgut',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 4,
                'town_name' => 'Mai Mahiu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 37,
                'town_name' => 'Nyahururu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Rumuruti',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Likoni',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Changamwe',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Maralal',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Kisauni',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Lokichogio',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Kakuma',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Webuye',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Wundanyi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Loiyangalani',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Mwingi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Ngong',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Kangundo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Molo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Londiani',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mlolongo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Litein',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Kimilili',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Mariakani',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Awasi',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Runyenjes',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Chemelil',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Malava',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Suneka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ogembo',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ukwala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Maua',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Chuka',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Juja',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Moyale',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Burnt Forest',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Maragua',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Ruai',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Naivasha',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Yala',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'county_id' => 1,
                'town_name' => 'Tabaka',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Malakisi',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Kipkelion',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Nyansiongo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Matuu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Kitengela',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [    'county_id' => 1,
                'town_name' => 'Makuyu',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Karuri',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Mlolongo',
                'created_by' => 1,
                'updated_by' => 1,
           ],
           [
                'county_id' => 1,
                'town_name' => 'Mwea',
                'created_by' => 1,
                'updated_by' => 1,
           ]
        ]);
    }
}
